# Generated by Django 2.2.11 on 2020-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200317_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
