# Generated by Django 2.2.11 on 2020-03-18 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200317_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.Country'),
        ),
    ]
